
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"  # Expose PostgreSQL on port 5433 externally
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Use a named volume to persist data
    networks:
      - conv.api  # Attach to the backend network
    restart: always


      

  conv.api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    networks:
      - conv.api 
    environment:
      - CONNECTION_STRING=postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable  # Connect to PostgreSQL on the internal Docker network
    depends_on:
      - postgres  

networks:
  conv.api:
    driver: bridge  # Use the bridge driver for communication between the services

volumes:
  postgres-data:  # Define a named volume for persistent PostgreSQL data
