// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateEntry(ctx context.Context, userUsername string) (Entry, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetDocument(ctx context.Context, id uuid.UUID) (Document, error)
	GetDocumentByFilename(ctx context.Context, filename string) ([]Document, error)
	GetDocumentByUsername(ctx context.Context, userUsername string) ([]GetDocumentByUsernameRow, error)
	GetEntry(ctx context.Context, id uuid.UUID) (Entry, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
